### PR TITLE
created all the customer endpoint requests.

### PR DESCRIPTION
**Pull request by gl3nda85**
This pull request needs some more commenting and maybe some tests but ive created all the customer end points

### CODE REVIEW

**Comment by mikeybeck** [comment]
Excellent, thanks for this!  I've taken a quick look and it seems good to me; I'll test it out tomorrow.

**Comment by gl3nda85** [comment]
all good im willing to help you complete the whole api, i would like to model some functions around the stripe on so i dont have to write different functions to get a customer object or something

**Comment by gl3nda85** [comment]
I have added in some more validation to responses and added another card function in, what do you use this library for?

**Comment by gl3nda85** [comment]
wait what did i miss

**Comment by mikeybeck** [comment]
Sorry I was unexpectedly busy the past week and am away at the moment which
is why I haven't merged your PRs.
I made and merged a PR myself the other day to urgently fix a bug.  Is
there a problem?

**Comment by gl3nda85** [comment]
oh i didnt realise what you did, ill have a look, what bug was it

**Comment by mikeybeck** [comment]
Ok cool thanks. It was my fault - in the exception responses I put a comma
instead of a fullstop. As a result, we had a problem with our system that I
simply could not track down due to lack of information. Fixing this enabled
me to figure it out.

**Comment by gl3nda85** [comment]
sweet, are we able to merge this now

**Comment by mikeybeck** [comment]
Not just yet sorry; I tested it just now and got an error from Square
saying the customer_id field is missing.  I checked the outgoing data and
saw that customer_id was null, and so was card_nonce.
I'm not sure what caused this but expect to test it further and hopefully
fix it tonight.
Are you not getting any errors?

**Comment by gl3nda85** [comment]
what function were you testing?

**Comment by mikeybeck** [comment]
The ChargeRequest function (with a saved customer/card).  It works when not
using a saved customer though.

The error returned is: Exception when creating transaction: [HTTP/1.1 400
Bad Request]
{"errors":[{"category":"INVALID_REQUEST_ERROR","code":"MISSING_REQUIRED_PARAMETER","detail":"Missing
required parameter.","field":"customer_id"}]}

**Comment by gl3nda85** [comment]
how do you create the charge object
i think you need to use 
payload = [
customerReference => '1',
customerCardId => '1'
]

**Comment by mikeybeck** [comment]
Ok I'll take a look, thanks

**Comment by mikeybeck** [comment]
Ah yeah I need to change 'customerId' to 'customerReference' to get it to
work.  Is there any benefit from this change?
I'd rather keep it the way it is because this is a breaking change, but it
appears noone else is using this repo at the moment so I suppose it's fine.

**Comment by gl3nda85** [comment]
it was to follow in line with the stripe repo. just so if you want to use stripe, square and other providers its more consistent, its needed in our implementation

**Comment by mikeybeck** [comment]
Oh yep.  We are using a couple of other providers also and have added a gateway class for each one to take care of the differences between them.
I've made a couple of modifications to our Square gateway class in order to be able to accept this PR.  I'll merge it now but won't tag the release until these modifications are on production.

**Pull request merged**
