### PR TITLE
Replace "square/connect" with "square/square"

### PR DESCRIPTION
**Pull request by ghost**
This pull request updates the retired Square Connect PHP SDK to the newer Square PHP SDK.

Comments welcome :)

cc: @mikeybeck

### CODE REVIEW

**Comment by Dolaned** [comment]
@deckbooks how can i run your branch while i wait for a merge

**Comment by mikeybeck** [comment]
Hey, sorry for the delay getting to this.
I'm testing it at the moment and all going well, will merge it early next week.

Thanks very much for contributing!

**Comment by Dolaned** [comment]
@mikeybeck i noticed the error handling in charge request doesnt actually return any data.
i get undefined index 'code',  im assuming its because getErrors() returns an array of error objects?

**Comment by mikeybeck** [comment]
@Dolaned 
`$result->getErrors()` returns null if there are no errors, in which case `($error = $result->getErrors())` is false, and a successful `ChargeResponse` is returned.
If the transaction is unsuccessful, a `ChargeResponse` is still returned.  You can get the code by calling the `getCode` function on it.  However, I see that the `ChargeResponse` class is missing the `getCode` function, so currently it'll always return null.

You're welcome to submit a PR to add the getCode function, otherwise I'll likely do it next week.

**Comment by mikeybeck** [comment]
The new Square PHP SDK deprecates the transactions API so I'm working on some changes to deal with this in the ListTransactionsRequest class.

**Comment by deckbooks** [comment]
Excellent thanks @mikeybeck for taking a look if I can be of any assistance let me know, we use this package a lot so are open to helping maintain it

**Comment by deckbooks** [comment]
@mikeybeck I've also reached out to Square for the following deprecated endpoints as there doesn't seem to be a replacement yet in the new SDK;

- deleteCustomerCard
- retrieveTransaction
- listRefunds
- listTransactions

**Comment by mikeybeck** [comment]
@deckbooks thanks!  

The Transactions API has been replaced with the Payments and Orders APIs.  There isn't a direct replacement for listTransactions, but the transaction data can be retrieved using the Payments API.  
I presume the other endpoints are similar.

**Comment by deckbooks** [comment]
Hi @mikeybeck I have the replacement calls from Square I'll start updating the deprecated ones over the next few days

**Comment by deckbooks** [comment]
Hi @mikeybeck I've updated the following if you could test;

- DeleteCardRequest.php to use new DisableCard API
- ListRefundsRequest.php to use new Refunds API
- Updated Square SDK to 14.1.0.20210915

I've you have time it would be good to discuss the deprecated TransactionRequest.php to new GetPayment API change, as there are quite a few changes to functionality that should be discussed for this endpoint.

**Comment by Dolaned** [comment]
Hey guys what api's do you want me to update?, list customer cards?

**Comment by deckbooks** [comment]
@Dolaned I think it’s almost complete, just needs @mikeybeck to review the latest deprecated to new API changes and discuss what to do with the current TransactionRequest.php functionality.

**Comment by mikeybeck** [comment]
Ah, I've done a bit of a review and it seems I've implemented the `purchase` function incorrectly.  I believe the `purchase` function in this repo currently does what the `completePurchase` function is supposed to do.  Is this your understanding also?
I'm a bit unsure because it seems the Omnipay implementation for the previous gateway I used (Windcave PxPost) also uses the `purchase` function to both authorise and capture the transaction.

I haven't been using the `completePurchase` function at all, which is why I hadn't noticed the Transactions API is still being used.  

What are your thoughts?

This PR looks good to me BTW.  Do you want me to wait to merge it after we've sorted out the Transactions API stuff, or is it good to go now?

**Comment by deckbooks** [comment]
Hi @mikeybeck The default state for Square is to complete and take the payment which is what the `purchase` function handles.

We could add a new set/get for `Autocomplete` default to true, to replicate the current functionality.

If `Autocomplete` is set to FALSE, we can pass that in the current `purchase` parameters, and provide a function to get the paymentId from the response. Once we have the paymentId we can then update the `completePurchase` function to use this SquareAPI https://github.com/square/square-php-sdk/blob/master/doc/apis/payments.md#complete-payment to complete the payment.

Doing this way we can keep the default capture payment now, as well as offer a new "approved" payment state and capture this later with the paymentId making a change to the `completePurchase` function and using the Complete Payment Square API.

What do you think?

**Comment by Alofoxx** [comment]
Hey @deckbooks @mikeybeck great work on getting things going on this upgrade to the library! 

Due to the recent retirement of the square API purchase() used to depend on, I have been working on this the last few days with the aim to have a stable build by end of week. 

I plan to make a 3.0.x version to push back to https://github.com/Transportersio/omnipay-square that will use current API methods and try to bring things into compliance with the Omnipay spec for at least the common params provided by Omnipay.

If you have time, I would appreciate any feedback on my PR's:

- main create payment work: https://github.com/Alofoxx/omnipay-square/pull/3
- a temporary PR to provide a diff from the new 3.x branch (which is based from your forks) against the current Transportersio/omnipay-square master : https://github.com/Alofoxx/omnipay-square/pull/2

**Comment by millnut** [comment]
I've just updated the DeckBooks fork again but happy to contribute @Alofoxx let's put a plan together

**Comment by Alofoxx** [comment]
Sure @millnut I have been running my main branch in prod and it has been stable 
We should probably get it buttoned up and documented

**Comment by millnut** [comment]
Sounds good @Alofoxx do we know if https://github.com/Transportersio/omnipay-square are likely to merge it we get the v3.0 branch ready? If we don't hear anything it might be worth contacting the omnipay repo and getting the recommended square integration changed.

**Comment by Alofoxx** [comment]
@millnut  They seem to have merged me before - I can start an issue asking about it. If we don't hear back after a while, we can submit a PR to the omnipay repo - it's pretty straightforward forward, and I have some other phpleague clients I maintain

Do you want to make some issues on my fork for anything you think we need to fix up for a proper release? we can get out of this thread perhaps. Does my fork have the lastest version of all forks?

**Comment by Alofoxx** [comment]
Just realized there are no issues on my repo so we can make a to-do list in this pr maybe? https://github.com/Transportersio/omnipay-square/pull/20

**Comment by millnut** [comment]
@Alofoxx I'm not sure let me check out your fork and compare differences with my fork and we'll build a to-do list in the PR.

I will need to check again but I believe the only remaining change was updating TransactionRequest.php and then some code standards/cleanup

**Pull request closed without merging**
